modLoader="javafml" #mandatory
loaderVersion="[38,)" #mandatory
issueTrackerURL="${issues_url}"
sourcesUrl="${sources_url}"
license="${license}"

[[mods]] #mandatory
    modId="${mod_id}"
    version="${version}"
    displayName="${mod_display_name}"
    displayURL="${homepage_url_forge}"
    authors="${mod_author}"
    credits="${mod_credits}"
    description='''${mod_description}'''
    logoFile="${logo_forge}"
    logoBlur=false

[dependencies]
"${mod_id}" = [
    { modId = "forge", mandatory = true, versionRange = "[47.1.0,47.1.4],[47.1.43,)", ordering = "NONE", side = "BOTH" },
    { modId = "minecraft", mandatory = true, versionRange = "[1.20.1,1.21)", ordering = "NONE", side = "BOTH" },
    { modId = "curios", mandatory = false, versionRange = "[5.3.1+1.20.1,)", ordering = "NONE" },
    { modId = "productivebees", mandatory = false, versionRange = "[0,)", ordering = "AFTER" },
    { modId = "resourcefulbees", mandatory = false, versionRange = "[0,)", ordering = "AFTER" },
    { modId = "ars_nouveau", mandatory = false, versionRange = "[0,)", ordering = "AFTER" },
    { modId = "resourcefulbees", mandatory = false, versionRange = "[1.20.1-4.9.0.152,)", ordering = "NONE" },
    { modId = "tombstone", mandatory = false, versionRange = "[0,)", ordering = "AFTER" },
    { modId = "structureessentials", mandatory = false, versionRange = "(,1.20.1-4.5),(1.20.1-4.5,)", ordering = "NONE" },
]