plugins {
    id 'net.fabricmc.fabric-loom'
}

repositories {
    exclusiveContent {
        forRepository {
            maven {
                url = "https://maven.terraformersmc.com/releases"
            }
        }
        filter {
            includeGroupAndSubgroups("com.terraformersmc")
        }
    }
    exclusiveContent {
        forRepository {
            maven {
                name = "MidnightDust"
                url = "https://maven.midnightdust.eu/releases"
            }
        }
        filter {
            includeGroupAndSubgroups("eu.midnightdust")
        }
    }
}

dependencies {
    minecraft "com.mojang:minecraft:${project.minecraft_version}"

    compileOnly(project.project(":common")) {
        transitive = false
    }

    implementation "net.fabricmc:fabric-loader:${project.fabric_loader_version}"
    implementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_api_version}"

    implementation("eu.midnightdust:midnightlib:${project.midnightlib}")
    localRuntime(compileOnly(include("earth.terrarium.athena:athena-fabric-${project.athena}")))
    localRuntime(compileOnly(include("com.teamresourceful.resourcefullib:resourcefullib-fabric-${project.resourcefullib}")))

    // COMPAT
    compileOnly("com.terraformersmc:modmenu:${project.mod_menu_version}") {
        transitive = false
    }
    localRuntime("com.terraformersmc:modmenu:${project.mod_menu_version}") {
        transitive = false
    }

    compileOnly("noobanidus.mods:lootr-fabric:${project.lootr}")
    //localRuntime("noobanidus.mods:lootr-fabric:${project.lootr}")

    //compileOnly("dev.emi:trinkets:${project.trinkets}") { transitive false }
    compileOnly("me.shedaniel.cloth:cloth-config-fabric:${project.cloth_config}")
    //localRuntime("me.shedaniel.cloth:cloth-config-fabric:${project.cloth_config}")
    compileOnly("curse.maven:restricted_portals-228266:${project.restricted_portals_file_id}")

    compileOnly("mezz.jei:jei-${project.jei_mc}-fabric:${project.jei}")
    compileOnly("mezz.jei:jei-${project.jei_mc}-common:${project.jei}")

    compileOnly("cc.cassian.rrv:reliable-recipe-viewer-fabric:${rrv}")

//    compileOnly("dev.emi:emi-fabric:${project.emi}:api")

    compileOnly("me.shedaniel:RoughlyEnoughItems-fabric:${project.rei}") { transitive = false }
    compileOnly("me.shedaniel:RoughlyEnoughItems-default-plugin:${project.rei}")

    compileOnly("com.mrcrayfish:backpacked-fabric:${project.backpacked}") { transitive = false  }
    compileOnly("com.mrcrayfish:framework-fabric:${project.framework}") { transitive = false }

//    localRuntime("com.telepathicgrunt:CommandStructures-Fabric:${project.commandstructures_fabric}")
//    localRuntime("com.telepathicgrunt:StructureVoidToggle-Fabric:${project.structurevoidtoggle_fabric}")
}

publishMods {
    file = tasks.jar.archiveFile
    modLoaders.add("fabric")

    File changeLog = rootProject.file("CHANGELOG.md")
    String changeLogText = changeLog.exists() ? changeLog.text : ""

    def uploadDependenciesCf = [
            "fabric-api": true,
            "midnightlib": true,
            "resourceful-lib": true,
            "better-advancements": false
    ]
    def uploadDependenciesMr = [
            "fabric-api": true,
            "midnightlib": true,
            "resourceful-lib": true,
            "better-advancements": false
    ]

    if (project.hasProperty('curseforge_id_fabric')) {
        curseforge('curseforgeFabric') {
            accessToken = providers.environmentVariable('CURSEFORGEKEY')
            projectId = project.findProperty('curseforge_id')
            minecraftVersions.add(project.minecraft_version)
            changelog = changeLogText
            changelogType = "markdown"
            client = true
            server = true

            uploadDependenciesCf.each { dep, required ->
                if (required) {
                    requires(dep)
                } else {
                    optional(dep)
                }
            }
        }
    }

    if (project.hasProperty('modrinth_id_fabric')) {
        modrinth('modrinthFabric') {
            accessToken = providers.environmentVariable('MODRINTH_TOKEN')
            projectId = project.findProperty('modrinth_id')
            minecraftVersions.add(project.minecraft_version)
            changelog = changeLogText

            dependencies {
                uploadDependenciesMr.each { dep, required ->
                    if (required) {
                        requires(dep)
                    } else {
                        optional(dep)
                    }
                }
            }
        }
    }
}

loom {
    mods {
        "${mod_id}" {
            // Tell Loom about each source set used by your mod here. This ensures that your mod's classes are properly transformed by Loader.
            sourceSet sourceSets.main
            sourceSet project.project(":common").sourceSets.main
        }
    }

    def awFile = project.file("src/main/resources/${mod_id}.accesswidener")
    if (awFile.exists()) {
        accessWidenerPath.set(awFile)
    }

    runs {
        configureEach {
            runDir("run")
            ideConfigGenerated(true)
        }

        client {
            client()
            setConfigName("Fabric Client")

            if (project.hasProperty('mc_uuid')) {
                programArg("--uuid=${project.findProperty('mc_uuid')}")
            }

            if (project.hasProperty('mc_username')) {
                programArg("--username=${project.findProperty('mc_username')}")
            }

            if (project.hasProperty('mc_java_agent_path')) {
                vmArg("-javaagent:${project.findProperty('mc_java_agent_path')}")
            }
        }

        server {
            server()
            setConfigName("Fabric Server")
            programArg('--nogui')
        }
    }
}

tasks.named("compileJava", JavaCompile) {
    source(project.project(":common").sourceSets.main.allJava)
}

tasks.named("javadoc", Javadoc).configure {
    source(project.project(":common").sourceSets.main.allJava)
}

tasks.named("sourcesJar", Jar) {
    from(project.project(":common").sourceSets.main.allSource)
}

processResources {
    from project.project(":common").sourceSets.main.resources
}
