plugins {
    id 'fabric-loom' version '1.10-SNAPSHOT'
}

repositories {
    maven {
        name = "ParchmentMC"
        url = "https://maven.parchmentmc.org"
        content {
            includeGroup "org.parchmentmc.data"
        }
    }
    maven {
        name = 'Ladysnake Mods'
        url = 'https://maven.ladysnake.org/releases'
        content {
            includeGroup 'io.github.ladysnake'
            includeGroupByRegex 'dev\\.onyxstudios.*'
        }
    }
    maven {
        url = 'https://maven.cafeteria.dev/releases/'
        content {
            includeGroup 'me.luligabi'
        }
    }
    maven {
        name = "TerraformersMC"
        url = "https://maven.terraformersmc.com/"
        content {
            includeGroupByRegex 'dev\\.emi.*'
            includeGroup 'com.terraformersmc'
        }
    }
}

dependencies {
    minecraft "com.mojang:minecraft:${project.minecraft_version}"
    mappings(loom.layered {
        it.officialMojangMappings()
        it.parchment("org.parchmentmc.data:parchment-${project.parchment_minecraft_version}:${project.parchment_mappings_version}@zip")
    })
    compileOnly(project(":common")) {
        transitive = false
    }

    modImplementation("net.fabricmc:fabric-loader:${project.fabric_loader_version}")
    modImplementation("net.fabricmc.fabric-api:fabric-api:${project.fabric_api_version}")

    modImplementation("maven.modrinth:midnightlib:${rootProject.midnightlib}")
    modImplementation("dev.onyxstudios.cardinal-components-api:cardinal-components-base:${rootProject.cardinal_components}")
    modImplementation("dev.onyxstudios.cardinal-components-api:cardinal-components-entity:${rootProject.cardinal_components}")
    include("dev.onyxstudios.cardinal-components-api:cardinal-components-base:${rootProject.cardinal_components}")
    include("dev.onyxstudios.cardinal-components-api:cardinal-components-entity:${rootProject.cardinal_components}")
    include("me.luligabi:NoIndium:${rootProject.noindium}")
    modRuntimeOnly(modCompileOnly(include("earth.terrarium.athena:athena-fabric-${rootProject.athena}")))
    include(implementation(annotationProcessor("io.github.llamalad7:mixinextras-fabric:${project.mixin_extras_version}")))

    modCompileOnly("com.terraformersmc:modmenu:${project.mod_menu}") {
        transitive = false
    }
    modLocalRuntime("com.terraformersmc:modmenu:${project.mod_menu}") {
        transitive = false
    }

    // COMPAT
    modCompileOnly("curse.maven:lootr_fabric-615106:${project.lootr_fabric_file_id}")
    //modRuntimeOnly("curse.maven:lootr_fabric-615106:${project.lootr_fabric_file_id}")

    modCompileOnly("maven.modrinth:modmenu:${rootProject.mod_menu}")
    modRuntimeOnly("maven.modrinth:modmenu:${rootProject.mod_menu}")

    modCompileOnly("mezz.jei:jei-${rootProject.jei_mc}-fabric:${rootProject.jei}")

    modCompileOnly("me.shedaniel:RoughlyEnoughItems-api:${rootProject.rei}")
    modCompileOnly("me.shedaniel:RoughlyEnoughItems-default-plugin:${rootProject.rei}")
    modCompileOnly("me.shedaniel.cloth:cloth-config-fabric:${rootProject.cloth_config}")

    modCompileOnly("dev.emi:trinkets:${trinkets}")

    //modLocalRuntime("dev.emi:emi-fabric:${rootProject.emi}")
    modCompileOnly "dev.emi:emi-fabric:${rootProject.emi}"

    modCompileOnly "curse.maven:restricted-portals-228266:${rootProject.restricted_portals_file_id}"

    modCompileOnly("maven.modrinth:sodium:${rootProject.sodium}")

    modCompileOnly("curse.maven:zenith-620928:${project.zenith_file_id}")

    modCompileOnly("maven.modrinth:projectile-damage-attribute:${rootProject.projectile_damage_attribute}-forge")

//    modLocalRuntime("curse.maven:huge-structure-blocks-474114:4803539")
//    modLocalRuntime("com.telepathicgrunt:CommandStructures:${project.commandstructures_fabric}")
//    modLocalRuntime("com.telepathicgrunt:StructureVoidToggle-Fabric:${project.structurevoidtoggle_fabric}")
}

publishMods {
    file = tasks.remapJar.archiveFile
    modLoaders.add("fabric")

    File changeLog = rootProject.file("CHANGELOG.md")
    String changeLogText = changeLog.exists() ? changeLog.text : ""

    def uploadDependenciesCf = [
            "fabric-api": true,
            "midnightlib": true,
            "better-advancements": false
    ]
    def uploadDependenciesMr = [
            "fabric-api": true,
            "midnightlib": true,
            "better-advancements": false
    ]

    if (project.hasProperty('curseforge_id_fabric')) {
        curseforge('curseforgeFabric') {
            accessToken = providers.environmentVariable('CURSEFORGEKEY')
            projectId = project.findProperty('curseforge_id_fabric')
            minecraftVersions.add(project.minecraft_version)
            changelog = changeLogText

            uploadDependenciesCf.each { dep, required ->
                if (required) {
                    requires(dep)
                } else {
                    optional(dep)
                }
            }
        }
    }

    if (project.hasProperty('modrinth_id_fabric')) {
        modrinth('modrinthFabric') {
            accessToken = providers.environmentVariable('MODRINTH_TOKEN')
            projectId = project.findProperty('modrinth_id_fabric')
            minecraftVersions.add(project.minecraft_version)
            changelog = changeLogText

            dependencies {
                uploadDependenciesMr.each { dep, required ->
                    if (required) {
                        requires(dep)
                    } else {
                        optional(dep)
                    }
                }
            }
        }
    }
}

loom {
    mods {
        "${mod_id}" {
            // Tell Loom about each source set used by your mod here. This ensures that your mod's classes are properly transformed by Loader.
            sourceSet sourceSets.main
            sourceSet project(":common").sourceSets.main
        }
    }

    def awFile = project(':common').file("src/main/resources/${mod_id}.accesswidener")
    if (awFile.exists()) {
        accessWidenerPath.set(awFile)
    }

    mixin {
        useLegacyMixinAp = false
    }

    runs {
        configureEach {
            runDir("run")
            ideConfigGenerated(true)
        }

        client {
            client()
            setConfigName("Fabric Client")

            if (project.hasProperty('mc_uuid')) {
                programArg("--uuid=${project.findProperty('mc_uuid')}")
            }

            if (project.hasProperty('mc_username')) {
                programArg("--username=${project.findProperty('mc_username')}")
            }

            if (project.hasProperty('mc_java_agent_path')) {
                vmArg("-javaagent:${project.findProperty('mc_java_agent_path')}")
            }
        }

        server {
            server()
            setConfigName("Fabric Server")
            programArg('--nogui')
        }
    }
}

tasks.named("compileJava", JavaCompile) {
    source(project(":common").sourceSets.main.allJava)
}

tasks.named("javadoc", Javadoc).configure {
    source(project(":common").sourceSets.main.allJava)
}

tasks.named("sourcesJar", Jar) {
    from(project(":common").sourceSets.main.allSource)
}

processResources {
    from project(":common").sourceSets.main.resources
}
