plugins {
    id "com.github.johnrengelman.shadow" version "7.1.2"
}

architectury {
    platformSetupLoomIde()
    fabric()
}

publishMods {
    file = tasks.remapJar.archiveFile
    modLoaders.add("fabric")

    File changeLog = rootProject.file("CHANGELOG.md")
    String changeLogText = changeLog.exists() ? changeLog.text : ""

    def uploadDependenciesCf = [
            "fabric-api": true,
            "midnightlib": true,
            "resourceful-lib": true,
            "better-advancements": false
    ]
    def uploadDependenciesMr = [
            "fabric-api": true,
            "midnightlib": true,
            "resourceful-lib": true,
            "better-advancements": false
    ]

    if (project.hasProperty('curseforge_id_fabric')) {
        curseforge('curseforgeFabric') {
            accessToken = providers.environmentVariable('CURSEFORGEKEY')
            projectId = project.findProperty('curseforge_id_fabric')
            minecraftVersions.add(project.minecraft_version)
            changelog = changeLogText
            changelogType = "markdown"
            client = true
            server = true

            uploadDependenciesCf.each { dep, required ->
                if (required) {
                    requires(dep)
                } else {
                    optional(dep)
                }
            }
        }
    }

    if (project.hasProperty('modrinth_id_fabric')) {
        modrinth('modrinthFabric') {
            accessToken = providers.environmentVariable('MODRINTH_TOKEN')
            projectId = project.findProperty('modrinth_id_fabric')
            minecraftVersions.add(project.minecraft_version)
            changelog = changeLogText

            dependencies {
                uploadDependenciesMr.each { dep, required ->
                    if (required) {
                        requires(dep)
                    } else {
                        optional(dep)
                    }
                }
            }
        }
    }
}

loom {
    accessWidenerPath = project(":common").loom.accessWidenerPath
}

configurations {
    common
    shadowCommon // Don't use shadow from the shadow plugin because we don't want IDEA to index this.
    compileClasspath.extendsFrom common
    runtimeClasspath.extendsFrom common
    developmentFabric.extendsFrom common
}

dependencies {
    // REQUIRED
    modImplementation "net.fabricmc:fabric-loader:${rootProject.fabric_loader_version}"
    modApi "net.fabricmc.fabric-api:fabric-api:${rootProject.fabric_api_version}"

    modImplementation("maven.modrinth:midnightlib:${rootProject.midnightlib}")

    modImplementation("dev.onyxstudios.cardinal-components-api:cardinal-components-base:${rootProject.cardinal_components}")
    modImplementation("dev.onyxstudios.cardinal-components-api:cardinal-components-entity:${rootProject.cardinal_components}")
    include("dev.onyxstudios.cardinal-components-api:cardinal-components-base:${rootProject.cardinal_components}")
    include("dev.onyxstudios.cardinal-components-api:cardinal-components-entity:${rootProject.cardinal_components}")

    include("me.luligabi:NoIndium:${rootProject.noindium}")

    modRuntimeOnly(modCompileOnly(include("earth.terrarium.athena:athena-fabric-${rootProject.athena}")))

    common(project(path: ":common", configuration: "namedElements")) { transitive false }
    shadowCommon(project(path: ":common", configuration: "transformProductionFabric")) { transitive false }
    common(project(path: ":fabric-base", configuration: "namedElements")) { transitive false }
    shadowCommon(project(path: ":fabric-base", configuration: "transformProductionFabric")) { transitive false }

    include(implementation(annotationProcessor("io.github.llamalad7:mixinextras-fabric:${rootProject.mixin_extras}")))


    // COMPAT
    modCompileOnly("curse.maven:lootr_fabric-615106:${project.lootr_fabric_file_id}")
    //modRuntimeOnly("curse.maven:lootr_fabric-615106:${project.lootr_fabric_file_id}")

    modCompileOnly("maven.modrinth:modmenu:${rootProject.mod_menu}")
    modRuntimeOnly("maven.modrinth:modmenu:${rootProject.mod_menu}")

    modCompileOnly("me.shedaniel.cloth:cloth-config-fabric:${rootProject.cloth_config}")

    //modLocalRuntime("dev.emi:emi-fabric:${rootProject.emi}")

//    modLocalRuntime("curse.maven:huge-structure-blocks-474114:4803539")
//    modLocalRuntime("com.telepathicgrunt:CommandStructures:${project.commandstructures_fabric}")
//    modLocalRuntime("com.telepathicgrunt:StructureVoidToggle-Fabric:${project.structurevoidtoggle_fabric}")
}

processResources {
    inputs.property "version", project.version

    filesMatching("META-INF/mods.toml") {
        expand "version": project.version
    }
}

shadowJar {
    exclude "architectury.common.json"
    configurations = [project.configurations.shadowCommon]
    archiveClassifier.set("dev-shadow")
}

remapJar {
    injectAccessWidener = true
    inputFile.set shadowJar.archiveFile
    dependsOn shadowJar
    archiveClassifier.set(null)
}

jar {
    archiveClassifier.set("dev")
}

sourcesJar {
    def commonSources = project(":common").sourcesJar
    dependsOn commonSources
    from commonSources.archiveFile.map { zipTree(it) }
}

components.java {
    withVariantsFromConfiguration(project.configurations.shadowRuntimeElements) {
        skip()
    }
}