plugins {
    id 'idea'
    id 'maven-publish'
    id 'me.modmuss50.mod-publish-plugin' version '2.0.0-beta.2' apply false
    id 'net.neoforged.moddev' version '2.0.141' apply false
    id 'net.fabricmc.fabric-loom-companion' version '1.17.9' apply false
    id 'net.fabricmc.fabric-loom' version '1.17.9' apply false
}

def javaVersion = 25

def ENV = System.getenv()
version = mod_version
group = mod_group_id

allprojects {
    repositories {
        exclusiveContent {
            forRepository {
                maven {
                    url = "https://www.cursemaven.com"
                }
            }
            filter {
                includeGroupAndSubgroups("curse.maven")
            }
        }
        exclusiveContent {
            forRepository {
                maven {
                    url = "https://api.modrinth.com/maven/"
                }
            }
            filter {
                includeGroupAndSubgroups("maven.modrinth")
            }
        }
        exclusiveContent {
            forRepository {
                maven {
                    url = "https://nexus.resourcefulbees.com/repository/maven-public/"
                }
            }
            filter {
                includeGroupAndSubgroups("com.telepathicgrunt")
                includeGroupAndSubgroups("com.teamresourceful.resourcefullib")
                includeGroupAndSubgroups("com.teamresourceful")
                includeGroupAndSubgroups("earth.terrarium.athena")
            }
        }
        exclusiveContent {
            forRepository {
                maven {
                    url = "https://maven.blamejared.com"
                }
            }
            filter {
                includeGroupAndSubgroups("mezz.jei")
                includeGroupAndSubgroups("noobanidus.mods")
                includeGroupAndSubgroups("noobanidus.mods")
            }
        }
        exclusiveContent {
            forRepository {
                maven {
                    name = "TerraformersMC"
                    url = "https://maven.terraformersmc.com/"
                }
            }
            filter {
                includeGroupByRegex("dev\\.emi.*")
            }
        }
        exclusiveContent {
            forRepository {
                maven {
                    url = "https://maven.shedaniel.me"
                }
            }
            filter {
                includeGroupAndSubgroups("me.shedaniel.cloth")
                includeGroupAndSubgroups("me.shedaniel")
            }
        }
        exclusiveContent {
            forRepository {
                maven {
                    url = "https://maven.architectury.dev/"
                }
            }
            filter {
                includeGroupAndSubgroups("dev.architectury")
            }
        }
        exclusiveContent {
            forRepository {
                maven {
                    url = "https://maven.blakesmods.com"
                }
            }
            filter {
                includeGroupAndSubgroups("com.blakebr0")
            }
        }
        exclusiveContent {
            forRepository {
                maven {
                    name = "Cassian's Maven"
                    url = uri("https://maven.cassian.cc")
                }
            }
            filter {
                includeGroupAndSubgroups("cc.cassian")
            }
        }
    }

    tasks.register('buildAndRelease') {
        dependsOn(tasks.build, tasks.publish)
    }
}

subprojects {
    apply plugin: 'java-library'
    apply plugin: 'maven-publish'
    apply plugin: 'me.modmuss50.mod-publish-plugin'
    project.group = rootProject.group
    project.version = rootProject.version

    base {
        archivesName.set(mod_id)
    }

    version = "${rootProject.mod_version}+${rootProject.minecraft_version}-${name}"

    repositories {}

    dependencies {
        compileOnly "org.jetbrains:annotations:${jetbrains_annotations_version}"
    }

    processResources {
        filteringCharset = "UTF-8"

        def expandProps = [
                "version"              : project.version,
                "maven_group_id"       : project.mod_group_id,
                "mod_id"               : project.mod_id,
                "mod_display_name"     : project.mod_name,
                "mod_description"      : project.mod_description,
                "sources_url"          : project.sources_url,
                "issues_url"           : project.issues_url,
                "license_url"          : project.license_url,
                "homepage_url"         : project.homepage_url,

                "minecraft_version"    : project.minecraft_version,
                "neoforge_version"     : project.neoforge_version,
                "fabric_loader_version": project.fabric_loader_version,
                "java_version"         : "${javaVersion}",
        ]

        filesMatching(['pack.mcmeta', '*.mod.json', 'META-INF/neoforge.mods.toml', '*.mixins.json']) {
            expand expandProps
        }
        inputs.properties(expandProps)
    }

    java {
        if (JavaVersion.current() < JavaVersion.toVersion(javaVersion)) {
            toolchain {
                languageVersion = JavaLanguageVersion.of(javaVersion)
            }
        } else {
            sourceCompatibility = JavaVersion.toVersion(javaVersion)
            targetCompatibility = JavaVersion.toVersion(javaVersion)
        }

        withSourcesJar()
//        withJavadocJar()
    }

    javadoc {
        // make javadoc not throw on mixin's '@reason'
        options.tags = ["reason"]
    }

    jar {
        def licenseFile1 = rootProject.file("LICENSE.txt")
        def licenseFile2 = rootProject.file("LICENSE_ASSETS.txt")
        inputs.file(licenseFile1)
        inputs.file(licenseFile2)

        from(licenseFile1) {
            rename { "LICENSE.txt" }
        }
        from(licenseFile2) {
            rename { "LICENSE_ASSETS.txt" }
        }
    }

    sourcesJar {
        def licenseFile1 = rootProject.file("LICENSE.txt")
        def licenseFile2 = rootProject.file("LICENSE_ASSETS.txt")
        inputs.file(licenseFile1)
        inputs.file(licenseFile2)

        from(licenseFile1) {
            rename { "LICENSE.txt" }
        }
        from(licenseFile2) {
            rename { "LICENSE_ASSETS.txt" }
        }
    }

    tasks.withType(JavaCompile).configureEach {
        options.release.set(javaVersion)
    }

    tasks.publishMods.mustRunAfter tasks.publish
    tasks.buildAndRelease.dependsOn(tasks.publish).dependsOn(tasks.publishMods)

    publishing {
        repositories {
            if (ENV.MAVEN_USER) {
                maven {
                    url = uri("https://nexus.resourcefulbees.com/repository/telepathicgrunt/")
                    credentials {
                        username = ENV.MAVEN_USER
                        password = ENV.MAVEN_PASS
                    }
                }
            }
        }

        publications {
            "mavenJava${project.name}"(MavenPublication) {
                from components.java
                artifactId = "${project.mod_id}"

                pom {
                    name = project.mod_name
                    description = project.mod_description
                    url = project.sources_url

                    scm {
                        connection = "git:${project.sources_url}.git"
                        developerConnection = "git:${project.sources_url}.git"
                        url = project.sources_url
                    }

                    licenses {
                        license {
                            name = 'LGPLv3 License'
                            url = project.license_url
                        }
                    }

                    developers {
                        developer {
                            id = 'telepathic_grunt'
                            name = 'TelepathicGrunt'
                            email = 'asarnesespam@gmail.com'
                        }
                    }
                }

            }
        }
    }

    publishMods {
        type = STABLE

        displayName = "${project.mod_name} v${rootProject.mod_version} (${rootProject.minecraft_version} MC ${name.capitalize()})"
        version = project.version

        def changeLogFile = project.file("CHANGELOG.md")
        changelog = changeLogFile.exists() ? changeLogFile.text : ""
    }

    task optimizePng {
        def pngPatterns = ["**/*.png"]
        doFirst {
            println 'Executing oxipng task...'
        }
        doLast {
            //Ensure the logo is minimized (we add this file to each jar)
            //Minimize any PNGs in the source sets
            for (dir in sourceSets.main.resources.srcDirs) {
                fileTree(dir: dir, includes: pngPatterns).each { minimizePNGFile(it) }
            }
            println 'Finished oxipng task...'
        }
    }
}

tasks.named('wrapper', Wrapper).configure {
    distributionType = Wrapper.DistributionType.BIN
}

//Minimize/optimize all png files, requires optipng on the PATH
// Credits: BrainStone
void minimizePNGFile(File file) {
    exec {
        executable "./oxipng.exe"
        args "-o", "6", "-i", "0", "--strip", "all", "-a", "-Z", file
    }
}

// IDEA no longer automatically downloads sources/javadoc jars for dependencies, so we need to explicitly enable the behavior.
idea {
    module {
        downloadSources = true
        downloadJavadoc = true
    }
}