plugins {
    id "architectury-plugin" version "3.4-SNAPSHOT"
    id "dev.architectury.loom" version "1.14-SNAPSHOT" apply false
    id 'io.github.juuxel.loom-vineflower' version '1.11.0' apply false
    id 'me.modmuss50.mod-publish-plugin' version '2.0.0-beta.2' apply false
    id "com.matthewprenger.cursegradle" version "1.4.0"
}

def javaVersion = 17
def ENV = System.getenv()
version = mod_version
group = mod_group_id

architectury {
    minecraft = rootProject.minecraft_version
}

allprojects {
    apply plugin: "java"
    apply plugin: "architectury-plugin"
    apply plugin: "maven-publish"

    archivesBaseName = rootProject.archives_base_name
    version = "${rootProject.mod_version}+${rootProject.minecraft_version}-${name}"
    group = rootProject.maven_group

    repositories {
        maven {
            url = 'https://maven.shedaniel.me'
            content {
                includeGroup 'me.shedaniel.cloth'
                includeGroup 'me.shedaniel'
            }
        }
        maven {
            url = 'https://www.cursemaven.com'
            content {
                includeGroup 'curse.maven'
            }
        }
        maven {
            url = 'https://api.modrinth.com/maven/'
            content {
                includeGroup 'maven.modrinth'
            }
        }
        maven {
            name = 'Ladysnake Mods'
            url = 'https://maven.ladysnake.org/releases'
            content {
                includeGroup 'io.github.ladysnake'
                includeGroupByRegex 'dev\\.onyxstudios.*'
            }
        }
        maven {
            name = "TerraformersMC"
            url = "https://maven.terraformersmc.com/"
            content {
                includeGroupByRegex 'dev\\.emi.*'
            }
        }
        maven {
            url = 'https://maven.blamejared.com'
            content {
                includeGroup 'mezz.jei'
            }
        }
        maven {
            url = 'https://nexus.resourcefulbees.com/repository/maven-public/'
            content {
                includeGroup 'com.telepathicgrunt'
                includeGroup 'earth.terrarium.athena'
            }
        }
        maven {
            url = "https://maven.theillusivec4.top/"
            content {
                includeGroup 'top.theillusivec4.curios'
            }
        }
        maven {
            url "https://maven.jamieswhiteshirt.com/libs-release"
            content {
                includeGroup "com.jamieswhiteshirt"
            }
        }
        maven {
            name = "ModMaven"
            url = "https://modmaven.dev"
            content {
                includeGroup 'com.hollingsworth.ars_nouveau'
            }
        }
//        maven {
//            url "https://maven.saps.dev/snapshots"
//            content {
//                includeGroup "dev.ftb.mods"
//            }
//        }
        maven {
            url 'https://modmaven.dev/'
            content {
                includeGroup 'mekanism'
            }
        }
        maven {
            url = 'https://maven.cafeteria.dev/releases/'
            content {
                includeGroup 'me.luligabi'
            }
        }
    }

    tasks.register('buildAndRelease') {
        dependsOn(tasks.build, tasks.publish)
    }
}


subprojects {
    apply plugin: "dev.architectury.loom"
    apply plugin: "com.matthewprenger.cursegradle"
    apply plugin: 'me.modmuss50.mod-publish-plugin'

    version = "${rootProject.mod_version}+${rootProject.minecraft_version}-${name}"

    loom {
        silentMojangMappingsLicense()
    }

    java {
        if (JavaVersion.current() < JavaVersion.toVersion(javaVersion)) {
            toolchain {
                languageVersion = JavaLanguageVersion.of(javaVersion)
            }
        } else {
            sourceCompatibility = JavaVersion.toVersion(javaVersion)
            targetCompatibility = JavaVersion.toVersion(javaVersion)
        }

        withSourcesJar()
//        withJavadocJar()
    }

    javadoc {
        // make javadoc not throw on mixin's '@reason'
        options.tags = ["reason"]
    }

    tasks.withType(JavaCompile).configureEach {
        options.release.set(javaVersion)
    }

    dependencies {
        minecraft "com.mojang:minecraft:${rootProject.minecraft_version}"
        mappings loom.officialMojangMappings()
    }

    jar {
        def licenseFile1 = rootProject.file("LICENSE.txt")
        def licenseFile2 = rootProject.file("LICENSE_ASSETS.txt")
        inputs.file(licenseFile1)
        inputs.file(licenseFile2)

        from(licenseFile1) {
            rename { "LICENSE.txt" }
        }
        from(licenseFile2) {
            rename { "LICENSE_ASSETS.txt" }
        }
    }

    publishMods {
        type = STABLE

        displayName = "${project.mod_name} v${rootProject.mod_version} (${rootProject.minecraft_version} MC ${name.capitalize()})"
        version = project.version

        def changeLogFile = project.file("CHANGELOG.md")
        changelog = changeLogFile.exists() ? changeLogFile.text : ""
    }

    tasks.withType(JavaCompile).configureEach {
        options.release.set(javaVersion)
    }

    tasks.publishMods.mustRunAfter tasks.publish
    tasks.buildAndRelease.dependsOn(tasks.publish).dependsOn(tasks.publishMods)

    publishing {
        repositories {
            if (ENV.MAVEN_USER) {
                maven {
                    url = uri("https://nexus.resourcefulbees.com/repository/telepathicgrunt/")
                    credentials {
                        username ENV.MAVEN_USER
                        password ENV.MAVEN_PASS
                    }
                }
            }
        }

        publications {
            "mavenJava${project.name}"(MavenPublication) {
                from components.java
                artifactId "${project.mod_id}"

                pom {
                    name = project.mod_name
                    description = project.mod_description
                    url = project.sources_url

                    scm {
                        connection = "git:${project.sources_url}.git"
                        developerConnection = "git:${project.sources_url}.git"
                        url = project.sources_url
                    }

                    licenses {
                        license {
                            name = 'LGPLv3 License'
                            url = project.license_url
                        }
                    }

                    developers {
                        developer {
                            id = 'telepathic_grunt'
                            name = 'TelepathicGrunt'
                            email = 'asarnesespam@gmail.com'
                        }
                    }
                }

            }
        }
    }

    task optimizePng {
        def pngPatterns = ["**/*.png"]
        doFirst {
            println 'Executing oxipng task...'
        }
        doLast {
            //Ensure the logo is minimized (we add this file to each jar)
            //Minimize any PNGs in the source sets
            for (dir in sourceSets.main.resources.srcDirs) {
                fileTree(dir: dir, includes: pngPatterns).each { minimizePNGFile(it) }
            }
            println 'Finished oxipng task...'
        }
    }
}

tasks.named('wrapper', Wrapper).configure {
    distributionType = Wrapper.DistributionType.BIN
}

//Minimize/optimize all png files, requires optipng on the PATH
// Credits: BrainStone
void minimizePNGFile(File file) {
    exec {
        executable "./oxipng.exe"
        args "-o", "6", "-i", "0", "--strip", "all", "-a", "-Z", file
    }
}

// IDEA no longer automatically downloads sources/javadoc jars for dependencies, so we need to explicitly enable the behavior.
idea {
    module {
        downloadSources = true
        downloadJavadoc = true
    }
}