org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=false

# Common
parchment_minecraft_version=1.21.9
parchment_mappings_version=2025.10.05
minecraft_version=1.21.10
neoform_version=1.21.10-20251010.172816
athena=1.21.6:4.4.0
midnightlib=1.8.3+1.21.9-fabric
resourcefullib=1.21.9:3.9.0

# NeoForge
neoforge_version=21.10.15-beta

# Fabric
fabric_loader_version=0.17.3
fabric_api_version=0.135.0+1.21.10
mod_menu_version=16.0.0-rc.1

# MC dependencies
jetbrains_annotations_version=26.0.1
mixin_version=0.15.4+mixin.0.8.7
mixin_extras_version=0.4.1
asm_version=9.7

## Mod Properties
mod_id=the_bumblezone
mod_name=The Bumblezone
mod_version=7.9.0
mod_description=A wonderful bee dimension mod with lots of new exploration and adventuring to do! Check out the advancements for how to play the mod!
sources_url=https://github.com/TelepathicGrunt/StructureLayoutOptimizer
issues_url=https://github.com/TelepathicGrunt/Bumblezone/issues
license_url=https://github.com/TelepathicGrunt/Bumblezone/blob/HEAD/LICENSE.txt
homepage_url=https://www.curseforge.com/projects/362479

# Publishing
mod_group_id=com.telepathicgrunt
curseforge_id_neoforge=362479
curseforge_id_fabric=363949
modrinth_id_neoforge=38tpSycf
modrinth_id_fabric=eA8SXqWL

# Compat Dependencies
mod_menu=14.0.0-rc.2
jei_mc=1.21.1
jei=19.21.0.247
rei=19.0.805
cloth_config=15.0.127
emi=1.1.21+1.21.1
architectury=16.1.4
curios=9.4.2+1.21.1
trinkets=3.10.0
mekanism=1.21.1-10.7.13.78
ars_nouveau=1.21.1:5.8.1.1060
lootr_version=1.21-1.10.34.88

# Compat Dependencies using CurseMaven
productivebees_file_id=6370406
buzzier_bees_file_id=6151411
restricted_portals_file_id=6194961
iron_jetpack_file_id=6191670
pneumaticcraft_file_id=6288626
ars_elemental_file_id=6381044
# Temporary until we figure out why I cannot remap the mod from their maven.
mekanism_file_id=6327955
framedblocks_file_id=6280708

# Helper Dependencies that only exist at runtime
commandstructures_neoforge=4.4.4+1.21.6
commandstructures_fabric=4.4.4+1.21.6
structurevoidtoggle_neoforge=4.5.1+1.21.6
structurevoidtoggle_fabric=4.5.1+1.21.6


