org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=false

# Common
parchment_minecraft_version=1.21.10
parchment_mappings_version=2025.10.12
minecraft_version=26.1-pre-2
neoform_version=26.1-pre-2-1
athena=1.21.6:4.4.1
midnightlib=1.9.2+1.21.10-fabric
resourcefullib=26.1-snapshot-11:4.0.0-beta.1

# NeoForge
neoforge_version=26.1.0.0-alpha.0+pre-2.20260313.154450

# Fabric
fabric_loader_version=0.18.4
fabric_api_version=0.143.14+26.1
mod_menu_version=18.0.0-alpha.5

# MC dependencies
jetbrains_annotations_version=26.0.1
mixin_version=0.15.4+mixin.0.8.7
mixin_extras_version=0.4.1
asm_version=9.7

## Mod Properties
mod_id=the_bumblezone
mod_name=The Bumblezone
mod_version=7.9.0
mod_description=A wonderful bee dimension mod with lots of new exploration and adventuring to do! Check out the advancements for how to play the mod!
sources_url=https://github.com/TelepathicGrunt/StructureLayoutOptimizer
issues_url=https://github.com/TelepathicGrunt/Bumblezone/issues
license_url=https://github.com/TelepathicGrunt/Bumblezone/blob/HEAD/LICENSE.txt
homepage_url=https://www.curseforge.com/projects/362479

# Publishing
mod_group_id=com.telepathicgrunt
curseforge_id_neoforge=362479
curseforge_id_fabric=363949
modrinth_id_neoforge=38tpSycf
modrinth_id_fabric=eA8SXqWL

# Compat Dependencies
jei_mc=1.21.11
jei=27.4.0.15
rei=21.11.814
cloth_config=21.11.153
emi=1.1.22+1.21.1
architectury=19.0.1
curios=11.0.1+1.21.5
trinkets=3.10.0
mekanism=1.21.1-10.7.13.78
ars_nouveau=1.21.1:5.8.1.1060
lootr_version=1.21.11-1.20.34.101

# Compat Dependencies using CurseMaven
productivebees_file_id=7267606
buzzier_bees_file_id=6961149
restricted_portals_file_id=6927080
iron_jetpack_file_id=7105279
pneumaticcraft_file_id=6817362
ars_elemental_file_id=7277838
framedblocks_file_id=7135071

# Helper Dependencies that only exist at runtime
commandstructures_neoforge=4.4.4+1.21.11
commandstructures_fabric=4.4.4+1.21.11
structurevoidtoggle_neoforge=4.5.3+1.21.11
structurevoidtoggle_fabric=4.5.3+1.21.11


