org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=false

# Common
parchment_minecraft_version=1.21.1
parchment_mappings_version=2024.11.17
minecraft_version=1.21.1
neoform_version=1.21.1-20240808.144430
athena=1.21:4.0.0
midnightlib=1.5.7-fabric
resourcefullib=1.21:3.0.12

# NeoForge
neoforge_version=21.1.216

# Fabric
fabric_loader_version=0.16.10
fabric_api_version=0.115.1+1.21.1
mod_menu_version=11.0.0

# MC dependencies
jetbrains_annotations_version=26.0.1
mixin_version=0.15.4+mixin.0.8.7
mixin_extras_version=0.4.1
asm_version=9.7

## Mod Properties
mod_id=the_bumblezone
mod_name=The Bumblezone
mod_version=7.11.7-beta
mod_description=A wonderful bee dimension mod with lots of new exploration and adventuring to do! Check out the advancements for how to play the mod!
sources_url=https://github.com/TelepathicGrunt/StructureLayoutOptimizer
issues_url=https://github.com/TelepathicGrunt/Bumblezone/issues
license_url=https://github.com/TelepathicGrunt/Bumblezone/blob/HEAD/LICENSE.txt
homepage_url=https://www.curseforge.com/projects/362479

# Publishing
mod_group_id=com.telepathicgrunt
curseforge_id_neoforge=362479
curseforge_id_fabric=363949
modrinth_id_neoforge=38tpSycf
modrinth_id_fabric=eA8SXqWL

# Compat Dependencies
jei_mc=1.21
jei=19.5.0.35
rei=16.0.729
cloth_config=15.0.127
emi=1.1.10+1.21
architectury=13.0.1
curios=9.4.2+1.21.1
trinkets=3.9.0
cardinal_components=6.0.0-pre2
projectile_damage_attribute=3.2.2+1.20.2
mekanism=1.21-10.6.1.45
ars_nouveau=1.21.1:5.8.2.1092
quark=4.0-458
zeta=1.0-19
caelus_version=7.0.0+1.21
geckolib_version=4.7.5.1
lootr_version=1.21-1.10.34.88

# Compat Dependencies using CurseMaven
pokecubeaio_version=5133485
productivebees_file_id=6154395
buzzier_bees_file_id=5229011
restricted_portals_file_id=5012474
iron_jetpack_file_id=5398991
pneumaticcraft_file_id=5321150
ars_elemental_file_id=6419081
framedblocks_file_id=5597081

# Helper Dependencies that only exist at runtime
commandstructures_neoforge=4.4.0+1.21
commandstructures_fabric=4.4.0+1.21
structurevoidtoggle_neoforge=4.4.1+1.21
structurevoidtoggle_fabric=4.4.1+1.21

