pluginManagement {
    repositories {
        maven { url "https://maven.architectury.dev/" }
        maven { url "https://maven.minecraftforge.net/" }
        maven {
            url = 'https://maven.fabricmc.net/'
            content {
                includeGroup 'net.fabricmc'
            }
        }
        gradlePluginPortal()
    }
}

gradle.lifecycle.beforeProject {
    tasks.withType(JavaCompile).configureEach {
        options.encoding = 'UTF-8' // Use the UTF-8 charset for Java compilation
        options.compilerArgs << "-Xmaxerrs" << "10000"
    }
}

include("common")
include("fabric")
include("fabric-base")
include("forge")

rootProject.name = "Bumblezone"
