package com.telepathicgrunt.the_bumblezone.modinit;

import com.telepathicgrunt.the_bumblezone.Bumblezone;
import com.telepathicgrunt.the_bumblezone.advancements.BlockStateSpecificTrigger;
import com.telepathicgrunt.the_bumblezone.advancements.CounterTrigger;
import com.telepathicgrunt.the_bumblezone.advancements.EntitySpecificTrigger;
import com.telepathicgrunt.the_bumblezone.advancements.GenericTrigger;
import com.telepathicgrunt.the_bumblezone.advancements.ItemSpecificTrigger;
import com.telepathicgrunt.the_bumblezone.advancements.KilledCounterTrigger;
import com.telepathicgrunt.the_bumblezone.advancements.TargetAdvancementDoneTrigger;
import dev.architectury.injectables.annotations.ExpectPlatform;
import net.minecraft.advancements.CriterionTrigger;
import net.minecraft.resources.ResourceLocation;
import org.apache.commons.lang3.NotImplementedException;

import java.util.function.Function;

public class BzCriterias {
    public static final ResourceLocation QUEENS_DESIRE_ROOT_ADVANCEMENT = new ResourceLocation(Bumblezone.MODID, "the_queens_desire/the_beginning");
    public static final ResourceLocation QUEENS_DESIRE_FINAL_ADVANCEMENT = new ResourceLocation(Bumblezone.MODID, "the_queens_desire/journeys_end");
    public static final ResourceLocation IS_NEAR_BEEHIVE_ADVANCEMENT = new ResourceLocation(Bumblezone.MODID, "teleportation/is_near_beehive");

    // CRITERIA TRIGGERS
    public static CounterTrigger BEE_BREEDING_TRIGGER;
    public static GenericTrigger BEENERGIZED_MAXED_TRIGGER;
    public static GenericTrigger BEE_CANNON_FULL_TRIGGER;
    public static GenericTrigger BEE_DROP_POLLEN_PUFF_TRIGGER;
    public static CounterTrigger BEE_FED_TRIGGER;
    public static EntitySpecificTrigger BEE_HIT_WRATH_OF_THE_HIVE_TRIGGER;
    public static CounterTrigger BEE_SAVED_BY_STINGER_TRIGGER;
    public static GenericTrigger BEE_STINGER_PARALYZE_TRIGGER;
    public static CounterTrigger BEE_STINGER_SHOOTER_TRIGGER;
    public static GenericTrigger BEE_QUEEN_FIRST_TRADE_TRIGGER;
    public static CounterTrigger BEE_QUEEN_TRADING_TRIGGER;
    public static CounterTrigger BEEHIVE_CRAFTED_TRIGGER;
    public static GenericTrigger BUMBLE_BEE_CHESTPLATE_MAX_FLIGHT_TRIGGER;
    public static GenericTrigger BUZZING_BRIEFCASE_FULL_TRIGGER;
    public static GenericTrigger BUZZING_BRIEFCASE_HEAL_TRIGGER;
    public static GenericTrigger BUZZING_BRIEFCASE_RELEASE_TRIGGER;
    public static GenericTrigger CARPENTER_BEE_BOOTS_MINED_BLOCKS_TRIGGER;
    public static GenericTrigger CARPENTER_BEE_BOOTS_WALL_HANGING_TRIGGER;
    public static BlockStateSpecificTrigger CARVE_WAX_TRIGGER;
    public static GenericTrigger CLEANUP_HONEY_WEB_TRIGGER;
    public static GenericTrigger CLEANUP_STICKY_HONEY_RESIDUE_TRIGGER;
    public static GenericTrigger COMB_CUTTER_EXTRA_DROPS_TRIGGER;
    public static GenericTrigger CRAFT_MULTI_POTION_POTION_CANDLE_TRIGGER;
    public static GenericTrigger CRYSTAL_CANNON_FULL_TRIGGER;
    public static GenericTrigger ENCHANT_CRYSTALLINE_FLOWER_TRIGGER;
    public static ItemSpecificTrigger ESSENCE_EVENT_REWARD_TRIGGER;
    public static GenericTrigger EXTEND_STRING_CURTAIN_TRIGGER;
    public static GenericTrigger FALLING_ON_POLLEN_BLOCK_TRIGGER;
    public static GenericTrigger FLOWER_HEADWEAR_WRATH_STRUCTURE_TRIGGER;
    public static ItemSpecificTrigger FOOD_REMOVED_WRATH_OF_THE_HIVE_TRIGGER;
    public static GenericTrigger GETTING_PROTECTION_TRIGGER;
    public static GenericTrigger GROW_CRYSTALLINE_FLOWER_TRIGGER;
    public static GenericTrigger HONEY_BEE_LEGGINGS_FLOWER_POLLEN_TRIGGER;
    public static GenericTrigger HONEY_BEE_LEGGINGS_POLLEN_REMOVAL_TRIGGER;
    public static CounterTrigger HONEY_BOTTLE_DRANK_TRIGGER;
    public static GenericTrigger HONEY_BUCKET_BEE_GROW_TRIGGER;
    public static GenericTrigger HONEY_BUCKET_BEE_LOVE_TRIGGER;
    public static GenericTrigger HONEY_BUCKET_BROOD_TRIGGER;
    public static GenericTrigger HONEY_COCOON_SILK_TOUCH_TRIGGER;
    public static GenericTrigger HONEY_COMPASS_USE_TRIGGER;
    public static GenericTrigger HONEY_CRYSTAL_SHIELD_BLOCK_INEFFECTIVELY_TRIGGER;
    public static GenericTrigger HONEY_PERMISSION_TRIGGER;
    public static CounterTrigger HONEY_SLIME_BRED_TRIGGER;
    public static GenericTrigger HONEY_SLIME_CREATION_TRIGGER;
    public static GenericTrigger HONEY_SLIME_HARVEST_TRIGGER;
    public static GenericTrigger IS_NEAR_BEEHIVE_TRIGGER;
    public static KilledCounterTrigger KILLED_COUNTER_TRIGGER;
    public static GenericTrigger LIGHT_SOUL_SUPER_CANDLE_TRIGGER;
    public static GenericTrigger POLLEN_PUFF_FIREBALL_TRIGGER;
    public static CounterTrigger POLLEN_PUFF_HIT_TRIGGER;
    public static GenericTrigger POLLEN_PUFF_MOOSHROOM_TRIGGER;
    public static CounterTrigger POLLEN_PUFF_SPAWN_FLOWERS_TRIGGER;
    public static GenericTrigger POLLEN_PUFF_PANDA_TRIGGER;
    public static GenericTrigger POLLEN_PUFF_POLLINATED_BEE_TRIGGER;
    public static GenericTrigger POLLEN_PUFF_POLLINATED_TALL_FLOWER_TRIGGER;
    public static GenericTrigger PROJECTILE_LIGHT_INSTANT_POTION_CANDLE_TRIGGER;
    public static EntitySpecificTrigger PROTECTION_OF_THE_HIVE_DEFENSE_TRIGGER;
    public static GenericTrigger QUEEN_BEEHEMOTH_TRIGGER;
    public static GenericTrigger ROOTMIN_FLOWER_SWAP_TRIGGER;
    public static GenericTrigger ROYAL_JELLY_BLOCK_PISTON_TRIGGER;
    public static GenericTrigger SEMPITERNAL_SANCTUM_ENTER_WITH_BEE_ESSENCE_TRIGGER;
    public static GenericTrigger SENTRY_WATCHER_SPAWN_EGG_USED_TRIGGER;
    public static GenericTrigger STINGER_SPEAR_KILLED_WITH_WITHER_TRIGGER;
    public static GenericTrigger STINGER_SPEAR_LONG_RANGE_KILL_TRIGGER;
    public static GenericTrigger STINGER_SPEAR_PARALYZE_BOSS_TRIGGER;
    public static GenericTrigger STINGER_SPEAR_PARALYZING_TRIGGER;
    public static GenericTrigger STINGER_SPEAR_POISONING_TRIGGER;
    public static GenericTrigger STINGLESS_BEE_HELMET_SUPER_SIGHT_TRIGGER;
    public static GenericTrigger SUGAR_WATER_NEXT_TO_SUGAR_CANE_TRIGGER;
    public static TargetAdvancementDoneTrigger TARGET_ADVANCEMENT_DONE_TRIGGER;
    public static GenericTrigger TELEPORT_OUT_OF_BUMBLEZONE_TRIGGER;
    public static GenericTrigger TELEPORT_TO_BUMBLEZONE_PEARL_TRIGGER;
    public static GenericTrigger TELEPORT_TO_BUMBLEZONE_PISTON_TRIGGER;
    public static GenericTrigger TRIGGER_REDSTONE_HONEY_WEB_TRIGGER;
    public static CounterTrigger VARIANT_BEE_BRIEFCASE_CAPTURE_TRIGGER;

    public static void registerCriteriaTriggers() {
        BEE_BREEDING_TRIGGER = register(new ResourceLocation(Bumblezone.MODID, "bee_breeding"), new CounterTrigger());
        BEENERGIZED_MAXED_TRIGGER = register(new ResourceLocation(Bumblezone.MODID, "beenergized_maxed"), new GenericTrigger());
        BEE_CANNON_FULL_TRIGGER = register(new ResourceLocation(Bumblezone.MODID, "bee_cannon_full"), new GenericTrigger());
        BEE_DROP_POLLEN_PUFF_TRIGGER = register(new ResourceLocation(Bumblezone.MODID, "bee_drop_pollen_puff"), new GenericTrigger());
        BEE_FED_TRIGGER = register(new ResourceLocation(Bumblezone.MODID, "bee_fed"), new CounterTrigger());
        BEE_HIT_WRATH_OF_THE_HIVE_TRIGGER = register(new ResourceLocation(Bumblezone.MODID, "bee_hit_wrath_of_the_hive"), new EntitySpecificTrigger());
        BEE_SAVED_BY_STINGER_TRIGGER = register(new ResourceLocation(Bumblezone.MODID, "bee_saved_by_stinger"), new CounterTrigger());
        BEE_STINGER_PARALYZE_TRIGGER = register(new ResourceLocation(Bumblezone.MODID, "bee_stinger_paralyze"), new GenericTrigger());
        BEE_STINGER_SHOOTER_TRIGGER = register(new ResourceLocation(Bumblezone.MODID, "bee_stinger_shooter"), new CounterTrigger());
        BEE_QUEEN_FIRST_TRADE_TRIGGER = register(new ResourceLocation(Bumblezone.MODID, "bee_queen_first_trade"), new GenericTrigger());
        BEE_QUEEN_TRADING_TRIGGER = register(new ResourceLocation(Bumblezone.MODID, "bee_queen_trading"), new CounterTrigger());
        BEEHIVE_CRAFTED_TRIGGER = register(new ResourceLocation(Bumblezone.MODID, "beehive_crafted"), new CounterTrigger());
        BUMBLE_BEE_CHESTPLATE_MAX_FLIGHT_TRIGGER = register(new ResourceLocation(Bumblezone.MODID, "bumble_bee_chestplate_max_flight"), new GenericTrigger());
        BUZZING_BRIEFCASE_FULL_TRIGGER = register(new ResourceLocation(Bumblezone.MODID, "buzzing_briefcase_full"), new GenericTrigger());
        BUZZING_BRIEFCASE_HEAL_TRIGGER = register(new ResourceLocation(Bumblezone.MODID, "buzzing_briefcase_heal"), new GenericTrigger());
        BUZZING_BRIEFCASE_RELEASE_TRIGGER = register(new ResourceLocation(Bumblezone.MODID, "buzzing_briefcase_release"), new GenericTrigger());
        CARPENTER_BEE_BOOTS_MINED_BLOCKS_TRIGGER = register(new ResourceLocation(Bumblezone.MODID, "carpenter_bee_boots_mined_blocks"), new GenericTrigger());
        CARPENTER_BEE_BOOTS_WALL_HANGING_TRIGGER = register(new ResourceLocation(Bumblezone.MODID, "carpenter_bee_boots_wall_hanging"), new GenericTrigger());
        CARVE_WAX_TRIGGER = register(new ResourceLocation(Bumblezone.MODID, "carve_wax"), new BlockStateSpecificTrigger());
        CLEANUP_HONEY_WEB_TRIGGER = register(new ResourceLocation(Bumblezone.MODID, "cleanup_honey_web"), new GenericTrigger());
        CLEANUP_STICKY_HONEY_RESIDUE_TRIGGER = register(new ResourceLocation(Bumblezone.MODID, "cleanup_sticky_honey_residue"), new GenericTrigger());
        COMB_CUTTER_EXTRA_DROPS_TRIGGER = register(new ResourceLocation(Bumblezone.MODID, "comb_cutter_extra_drops"), new GenericTrigger());
        CRAFT_MULTI_POTION_POTION_CANDLE_TRIGGER = register(new ResourceLocation(Bumblezone.MODID, "craft_multi_potion_potion_candle"), new GenericTrigger());
        CRYSTAL_CANNON_FULL_TRIGGER = register(new ResourceLocation(Bumblezone.MODID, "crystal_cannon_full"), new GenericTrigger());
        ENCHANT_CRYSTALLINE_FLOWER_TRIGGER = register(new ResourceLocation(Bumblezone.MODID, "enchant_crystalline_flower"), new GenericTrigger());
        ESSENCE_EVENT_REWARD_TRIGGER = register(new ResourceLocation(Bumblezone.MODID, "essence_event_reward"), new ItemSpecificTrigger());
        EXTEND_STRING_CURTAIN_TRIGGER = register(new ResourceLocation(Bumblezone.MODID, "extend_string_curtain"), new GenericTrigger());
        FALLING_ON_POLLEN_BLOCK_TRIGGER = register(new ResourceLocation(Bumblezone.MODID, "fall_onto_pollen_pile"), new GenericTrigger());
        FLOWER_HEADWEAR_WRATH_STRUCTURE_TRIGGER = register(new ResourceLocation(Bumblezone.MODID, "flower_headwear_wrath_structure"), new GenericTrigger());
        FOOD_REMOVED_WRATH_OF_THE_HIVE_TRIGGER = register(new ResourceLocation(Bumblezone.MODID, "food_removed_wrath_of_the_hive"), new ItemSpecificTrigger());
        GETTING_PROTECTION_TRIGGER = register(new ResourceLocation(Bumblezone.MODID, "getting_protection"), new GenericTrigger());
        GROW_CRYSTALLINE_FLOWER_TRIGGER = register(new ResourceLocation(Bumblezone.MODID, "grow_crystalline_flower"), new GenericTrigger());
        HONEY_BEE_LEGGINGS_FLOWER_POLLEN_TRIGGER = register(new ResourceLocation(Bumblezone.MODID, "honey_bee_leggings_flower_pollen"), new GenericTrigger());
        HONEY_BEE_LEGGINGS_POLLEN_REMOVAL_TRIGGER = register(new ResourceLocation(Bumblezone.MODID, "honey_bee_leggings_pollen_removal"), new GenericTrigger());
        HONEY_BOTTLE_DRANK_TRIGGER = register(new ResourceLocation(Bumblezone.MODID, "honey_bottle_drank"), new CounterTrigger());
        HONEY_BUCKET_BEE_GROW_TRIGGER = register(new ResourceLocation(Bumblezone.MODID, "honey_bucket_bee_grow"), new GenericTrigger());
        HONEY_BUCKET_BEE_LOVE_TRIGGER = register(new ResourceLocation(Bumblezone.MODID, "honey_bucket_bee_love"), new GenericTrigger());
        HONEY_BUCKET_BROOD_TRIGGER = register(new ResourceLocation(Bumblezone.MODID, "honey_bucket_brood"), new GenericTrigger());
        HONEY_COCOON_SILK_TOUCH_TRIGGER = register(new ResourceLocation(Bumblezone.MODID, "honey_cocoon_silk_touch"), new GenericTrigger());
        HONEY_COMPASS_USE_TRIGGER = register(new ResourceLocation(Bumblezone.MODID, "honey_compass_use"), new GenericTrigger());
        HONEY_CRYSTAL_SHIELD_BLOCK_INEFFECTIVELY_TRIGGER = register(new ResourceLocation(Bumblezone.MODID, "honey_crystal_shield_block_ineffectively"), new GenericTrigger());
        HONEY_PERMISSION_TRIGGER = register(new ResourceLocation(Bumblezone.MODID, "honey_permission"), new GenericTrigger());
        HONEY_SLIME_BRED_TRIGGER = register(new ResourceLocation(Bumblezone.MODID, "honey_slime_bred"), new CounterTrigger());
        HONEY_SLIME_CREATION_TRIGGER = register(new ResourceLocation(Bumblezone.MODID, "honey_slime_creation"), new GenericTrigger());
        HONEY_SLIME_HARVEST_TRIGGER = register(new ResourceLocation(Bumblezone.MODID, "honey_slime_harvest"), new GenericTrigger());
        IS_NEAR_BEEHIVE_TRIGGER = register(new ResourceLocation(Bumblezone.MODID, "is_near_beehive"), new GenericTrigger());
        KILLED_COUNTER_TRIGGER = register(new ResourceLocation(Bumblezone.MODID, "killed_counter"), new KilledCounterTrigger());
        LIGHT_SOUL_SUPER_CANDLE_TRIGGER = register(new ResourceLocation(Bumblezone.MODID, "light_soul_potion_candle"), new GenericTrigger());
        POLLEN_PUFF_FIREBALL_TRIGGER = register(new ResourceLocation(Bumblezone.MODID, "pollen_puff_fireball"), new GenericTrigger());
        POLLEN_PUFF_HIT_TRIGGER = register(new ResourceLocation(Bumblezone.MODID, "pollen_puff_hit"), new CounterTrigger());
        POLLEN_PUFF_MOOSHROOM_TRIGGER = register(new ResourceLocation(Bumblezone.MODID, "pollen_puff_mooshroom"), new GenericTrigger());
        POLLEN_PUFF_SPAWN_FLOWERS_TRIGGER = register(new ResourceLocation(Bumblezone.MODID, "pollen_puff_spawn_flower"), new CounterTrigger());
        POLLEN_PUFF_PANDA_TRIGGER = register(new ResourceLocation(Bumblezone.MODID, "pollen_puff_panda"), new GenericTrigger());
        POLLEN_PUFF_POLLINATED_BEE_TRIGGER = register(new ResourceLocation(Bumblezone.MODID, "pollen_puff_pollinate_bee"), new GenericTrigger());
        POLLEN_PUFF_POLLINATED_TALL_FLOWER_TRIGGER = register(new ResourceLocation(Bumblezone.MODID, "pollen_puff_pollinate_tall_flower"), new GenericTrigger());
        PROJECTILE_LIGHT_INSTANT_POTION_CANDLE_TRIGGER = register(new ResourceLocation(Bumblezone.MODID, "projectile_light_instant_potion_candle"), new GenericTrigger());
        PROTECTION_OF_THE_HIVE_DEFENSE_TRIGGER = register(new ResourceLocation(Bumblezone.MODID, "protection_of_the_hive_defense"), new EntitySpecificTrigger());
        QUEEN_BEEHEMOTH_TRIGGER = register(new ResourceLocation(Bumblezone.MODID, "created_queen_beehemoth"), new GenericTrigger());
        ROOTMIN_FLOWER_SWAP_TRIGGER = register(new ResourceLocation(Bumblezone.MODID, "rootmin_flower_swap"), new GenericTrigger());
        ROYAL_JELLY_BLOCK_PISTON_TRIGGER = register(new ResourceLocation(Bumblezone.MODID, "royal_jelly_block_piston"), new GenericTrigger());
        SEMPITERNAL_SANCTUM_ENTER_WITH_BEE_ESSENCE_TRIGGER = register(new ResourceLocation(Bumblezone.MODID, "sempiternal_sanctum_enter_with_bee_essence"), new GenericTrigger());
        SENTRY_WATCHER_SPAWN_EGG_USED_TRIGGER = register(new ResourceLocation(Bumblezone.MODID, "sentry_watcher_spawn_egg_used"), new GenericTrigger());
        STINGER_SPEAR_KILLED_WITH_WITHER_TRIGGER = register(new ResourceLocation(Bumblezone.MODID, "stinger_spear_killed_with_wither"), new GenericTrigger());
        STINGER_SPEAR_LONG_RANGE_KILL_TRIGGER = register(new ResourceLocation(Bumblezone.MODID, "stinger_spear_long_range_kill"), new GenericTrigger());
        STINGER_SPEAR_PARALYZE_BOSS_TRIGGER = register(new ResourceLocation(Bumblezone.MODID, "stinger_spear_paralyze_boss"), new GenericTrigger());
        STINGER_SPEAR_PARALYZING_TRIGGER = register(new ResourceLocation(Bumblezone.MODID, "stinger_spear_paralyzing"), new GenericTrigger());
        STINGER_SPEAR_POISONING_TRIGGER = register(new ResourceLocation(Bumblezone.MODID, "stinger_spear_poisoning"), new GenericTrigger());
        STINGLESS_BEE_HELMET_SUPER_SIGHT_TRIGGER = register(new ResourceLocation(Bumblezone.MODID, "stingless_bee_helmet_super_sight"), new GenericTrigger());
        SUGAR_WATER_NEXT_TO_SUGAR_CANE_TRIGGER = register(new ResourceLocation(Bumblezone.MODID, "sugar_water_next_to_sugar_cane"), new GenericTrigger());
        TARGET_ADVANCEMENT_DONE_TRIGGER = register(new ResourceLocation(Bumblezone.MODID, "target_advancement_done"), new TargetAdvancementDoneTrigger());
        TELEPORT_OUT_OF_BUMBLEZONE_TRIGGER = register(new ResourceLocation(Bumblezone.MODID, "teleport_out_of_bumblezone"), new GenericTrigger());
        TELEPORT_TO_BUMBLEZONE_PEARL_TRIGGER = register(new ResourceLocation(Bumblezone.MODID, "teleport_to_bumblezone_pearl"), new GenericTrigger());
        TELEPORT_TO_BUMBLEZONE_PISTON_TRIGGER = register(new ResourceLocation(Bumblezone.MODID, "teleport_to_bumblezone_piston"), new GenericTrigger());
        TRIGGER_REDSTONE_HONEY_WEB_TRIGGER = register(new ResourceLocation(Bumblezone.MODID, "trigger_redstone_honey_web"), new GenericTrigger());
        VARIANT_BEE_BRIEFCASE_CAPTURE_TRIGGER = register(new ResourceLocation(Bumblezone.MODID, "variant_bee_briefcase_capture"), new CounterTrigger());
    }

    @ExpectPlatform
    private static <T extends CriterionTrigger<?>> T register(ResourceLocation registryName, T criterionTrigger) {
        throw new NotImplementedException("CriterionTriggerRegistry.register");
    }
}
