plugins {
    id 'net.neoforged.moddev.legacyforge' version '2.0.88'
}

repositories {
    maven { url = 'https://maven.fabricmc.net' }
}

dependencies {
    compileOnly(project(path: ':common', configuration: 'namedElements')) {
        transitive = false
    }

    annotationProcessor 'net.fabricmc:sponge-mixin:0.13.0+mixin.0.8.5'

    annotationProcessor "io.github.llamalad7:mixinextras-common:${project.mixin_extras_version}"
    compileOnly("io.github.llamalad7:mixinextras-common:${project.mixin_extras_version}")
    implementation("io.github.llamalad7:mixinextras-forge:${project.mixin_extras_version}")

    modRuntimeOnly(modCompileOnly("earth.terrarium.athena:athena-forge-${project.athena}"))
    jarJar("earth.terrarium.athena:athena-forge-${project.athena}")

    // COMPAT
    modCompileOnly("curse.maven:iron_jetpack-284497:${project.iron_jetpack_file_id}")
    modCompileOnly("curse.maven:pneumaticcraft-281849:${project.pneumaticcraft_file_id}")

    modCompileOnly("curse.maven:pokecube_aio-285121:${project.pokecubeaio_version}")

    modCompileOnly("curse.maven:productive_bees-377897:${project.productivebees_file_id}")
    //runtimeOnly("curse.maven:productive_bees-377897:${project.productivebees_file_id}")

    modCompileOnly("curse.maven:lootr-361276:${project.lootr_file_id}")
    //runtimeOnly("curse.maven:lootr-361276:${project.lootr_file_id}")

    modCompileOnly("curse.maven:pokecube_aio-285121:${project.pokecubeaio_version}")

    modCompileOnly("curse.maven:buzzier_bees-355458:${project.buzzier_bees_file_id}")

    modCompileOnly("com.hollingsworth.ars_nouveau:ars_nouveau-${project.ars_nouveau}")
    modCompileOnly("curse.maven:ars_elemental-561470:${project.ars_elemental_file_id}")
    modCompileOnly("curse.maven:mekanism-268560:${project.mekanism_file_id}")
    modCompileOnly("curse.maven:apotheosis-313970:${project.apotheosis_file_id}")
    modCompileOnly("top.theillusivec4.curios:curios-forge:${project.curios}:api")

    modCompileOnly("mezz.jei:jei-${project.jei_mc}-forge-api:${project.jei}") { transitive = false }
    modCompileOnly("mezz.jei:jei-${project.jei_mc}-common-api:${project.jei}") { transitive = false }
    modCompileOnly("me.shedaniel:RoughlyEnoughItems-api:${project.rei}") { transitive = false }
    modCompileOnly("me.shedaniel:RoughlyEnoughItems-default-plugin:${project.rei}") { transitive = false }
    modCompileOnly("me.shedaniel.cloth:cloth-config-forge:${project.cloth_config}")
    modCompileOnly("dev.architectury:architectury:${project.architectury}")

    modCompileOnly("maven.modrinth:projectile-damage-attribute:${project.projectile_damage_attribute}-forge") { transitive = false }

    // runtimeOnly("curse.maven:better-advancements-272515:4631253")
    // runtimeOnly("curse.maven:spit-it-out-857141:4614678")
    // runtimeOnly("curse.maven:atlasviewer-633577:4597419")

    //compileOnly("mekanism:Mekanism:${project.mekanism}:api")
//    runtimeOnly("mekanism:Mekanism:${project.mekanism}")// core
//    runtimeOnly("mekanism:Mekanism:${project.mekanism}:additions")// Mekanism: Additions
//    runtimeOnly("mekanism:Mekanism:${project.mekanism}:generators")// Mekanism: Generators
//    runtimeOnly("mekanism:Mekanism:${project.mekanism}:tools")// Mekanism: Tools

    //compileOnly("dev.emi:emi-forge:${emi}:api")
    //runtimeOnly("dev.emi:emi-forge:${emi}")

    //runtimeOnly("me.shedaniel.cloth:cloth-config-forge:${project.cloth_config}")
    //runtimeOnly("dev.architectury:architectury-forge:${project.architectury}")
    //runtimeOnly("curse.maven:travelersbackpacks-321117:${project.travelersbackpacks_file_id}")
    //runtimeOnly("top.theillusivec4.curios:curios-forge:${project.curios}")

    // runtimeOnly("curse.maven:huge-structure-blocks-474114:4803547")
    // runtimeOnly("curse.maven:worldedit-225608:4586218")
    // runtimeOnly("com.telepathicgrunt:CommandStructures-Forge:${project.commandstructures_forge}")
    // runtimeOnly("com.telepathicgrunt:StructureVoidToggle-Forge:${project.structurevoidtoggle_forge}")

//    runtimeOnly(compileOnly("curse.maven:craziness-awakened-963163:6524580"))
//    runtimeOnly("curse.maven:attributefix-280510:4911084")
//    implementation("com.eliotlash.mclib:mclib:20")
//    runtimeOnly("software.bernie.geckolib:geckolib-forge-1.20.1:4.7.1.2")
//    runtimeOnly("curse.maven:pehkui-319596:5393101")
}

legacyForge {
    version = "${project.forge_version}"

    runs {
        client {
            client()
            systemProperty 'mixin.env.remapRefMap', 'true'
            systemProperty 'mixin.env.refMapRemappingFile', project.layout.buildDirectory.get().file('createSrgToMcp/output.srg').asFile.absolutePath
        }

        server {
            server()
            systemProperty 'mixin.env.remapRefMap', 'true'
            systemProperty 'mixin.env.refMapRemappingFile', project.layout.buildDirectory.get().file('createSrgToMcp/output.srg').asFile.absolutePath
        }
    }
    mods {
        modServerRun {
            sourceSet sourceSets.main
            sourceSet project(":common").sourceSets.main
        }
    }
}

publishMods {
    file = tasks.reobfJar.archiveFile
    modLoaders.add("forge")

    File changeLog = rootProject.file("CHANGELOG.md")
    String changeLogText = changeLog.exists() ? changeLog.text : ""

    def uploadDependenciesCf = [
        "better-advancements": false
    ]
    def uploadDependenciesMr = [
        "better-advancements": false
    ]

    if (project.hasProperty('curseforge_id_forge')) {
        curseforge('CurseforgeForge') {
            accessToken = providers.environmentVariable('CURSEFORGEKEY')
            projectId = project.findProperty('curseforge_id_forge')
            minecraftVersions.add(project.minecraft_version)
            changelog = changeLogText

            uploadDependenciesCf.each { dep, required ->
                if (required) {
                    requires(dep)
                } else {
                    optional(dep)
                }
            }
        }
    }

    if (project.hasProperty('modrinth_id_forge')) {
        modrinth('modrinthForge') {
            accessToken = accessToken = providers.environmentVariable('MODRINTH_TOKEN')
            projectId = project.findProperty('modrinth_id_forge')
            minecraftVersions.add(project.minecraft_version)
            changelog = changeLogText

            dependencies {
                uploadDependenciesMr.each { dep, required ->
                    if (required) {
                        requires(dep)
                    } else {
                        optional(dep)
                    }
                }
            }
        }
    }
}

mixin {
    add(sourceSets.main, "${mod_id}.refmap.json")

    config("${mod_id}-common.mixins.json")
    config("${mod_id}-forge.mixins.json")
}

tasks.named("compileJava", JavaCompile) {
    source(project(":common").sourceSets.main.allJava)
}

tasks.named("javadoc", Javadoc) {
    source(project(":common").sourceSets.main.allJava)
}

tasks.named("sourcesJar", Jar) {
    from(project(":common").sourceSets.main.allSource)
}

processResources {
    from project(":common").sourceSets.main.resources
}

jar {
    manifest {
        attributes([
                "MixinConfigs": "${project.mod_id}-common.mixins.json,${project.mod_id}-forge.mixins.json"
        ])
    }
}

publishing {
    publications {
        "mavenJava"(MavenPublication) {
            from components.java
        }
    }
}
