plugins {
    id 'net.neoforged.moddev.legacyforge' version '2.0.142'
}

repositories {
    maven { url = 'https://maven.fabricmc.net' }
    exclusiveContent {
        forRepository {
            maven {
                name = "ModMaven"
                url = "https://modmaven.dev"
            }
        }
        filter {
            includeGroupAndSubgroups("com.hollingsworth.ars_nouveau")
            includeGroupAndSubgroups("mekanism")
        }
    }
    exclusiveContent {
        forRepository {
            maven {
                name = "C4's Maven"
                url = "https://maven.theillusivec4.top/"
            }
        }
        filter {
            includeGroupAndSubgroups("top.theillusivec4.curios")
            includeGroupAndSubgroups("com.illusivesoulworks.caelus")
        }
    }
    exclusiveContent {
        forRepository {
            maven {
                name = 'GeckoLib'
                url = 'https://dl.cloudsmith.io/public/geckolib3/geckolib/maven/'
            }
        }
        filter {
            includeGroup('software.bernie.geckolib')
        }
    }
    maven {
        url "https://maven.jamieswhiteshirt.com/libs-release"
        content {
            includeGroup "com.jamieswhiteshirt"
        }
    }
}

dependencies {
    compileOnly(project(':common')) {
        transitive = false
    }

    runtimeOnly(compileOnly(jarJar("earth.terrarium.athena:athena-forge-${project.athena}")))

    annotationProcessor 'net.fabricmc:sponge-mixin:0.13.0+mixin.0.8.5'
    annotationProcessor "io.github.llamalad7:mixinextras-common:${project.mixin_extras_version}"
    compileOnly("io.github.llamalad7:mixinextras-common:${project.mixin_extras_version}")
    implementation("io.github.llamalad7:mixinextras-forge:${project.mixin_extras_version}")
    jarJar("io.github.llamalad7:mixinextras-forge:${project.mixin_extras_version}")

    // COMPAT
    compileOnly("curse.maven:iron_jetpack-284497:${project.iron_jetpack_file_id}")
    compileOnly("curse.maven:pneumaticcraft-281849:${project.pneumaticcraft_file_id}")

    compileOnly("curse.maven:pokecube_aio-285121:${project.pokecubeaio_version}")

    compileOnly("curse.maven:productive_bees-377897:${project.productivebees_file_id}")
    //runtimeOnly("curse.maven:productive_bees-377897:${project.productivebees_file_id}")

    compileOnly("curse.maven:lootr-361276:${project.lootr_file_id}")
    //runtimeOnly("curse.maven:lootr-361276:${project.lootr_file_id}")

    compileOnly("curse.maven:pokecube_aio-285121:${project.pokecubeaio_version}")

    compileOnly("curse.maven:buzzier_bees-355458:${project.buzzier_bees_file_id}")

    compileOnly("com.hollingsworth.ars_nouveau:ars_nouveau-${project.ars_nouveau}")
    compileOnly("curse.maven:ars_elemental-561470:${project.ars_elemental_file_id}")
    compileOnly("curse.maven:mekanism-268560:${project.mekanism_file_id}")
    compileOnly("curse.maven:apotheosis-313970:${project.apotheosis_file_id}")
    compileOnly("top.theillusivec4.curios:curios-forge:${project.curios}:api")

    // runtimeOnly("curse.maven:better-advancements-272515:4631253")
    // runtimeOnly("curse.maven:spit-it-out-857141:4614678")
    // runtimeOnly("curse.maven:atlasviewer-633577:4597419")

    //compileOnly("mekanism:Mekanism:${project.mekanism}:api")
//    runtimeOnly("mekanism:Mekanism:${project.mekanism}")// core
//    runtimeOnly("mekanism:Mekanism:${project.mekanism}:additions")// Mekanism: Additions
//    runtimeOnly("mekanism:Mekanism:${project.mekanism}:generators")// Mekanism: Generators
//    runtimeOnly("mekanism:Mekanism:${project.mekanism}:tools")// Mekanism: Tools

    //runtimeOnly("mezz.jei:jei-${project.jei_mc}-forge:${project.jei}")
    //runtimeOnly("mezz.jei:jei-${project.jei_mc}-common:${project.jei}")

    //compileOnly("dev.emi:emi-forge:${emi}:api")
    //runtimeOnly("dev.emi:emi-forge:${emi}")

    //runtimeOnly("me.shedaniel.cloth:cloth-config-forge:${project.cloth_config}")
    //runtimeOnly("dev.architectury:architectury-forge:${project.architectury}")
    //runtimeOnly("curse.maven:travelersbackpacks-321117:${project.travelersbackpacks_file_id}")
    //runtimeOnly("top.theillusivec4.curios:curios-forge:${project.curios}")

    // runtimeOnly("curse.maven:huge-structure-blocks-474114:4803547")
    // runtimeOnly("curse.maven:worldedit-225608:4586218")
    // runtimeOnly("com.telepathicgrunt:CommandStructures-Forge:${project.commandstructures_forge}")
    // runtimeOnly("com.telepathicgrunt:StructureVoidToggle-Forge:${project.structurevoidtoggle_forge}")
}

legacyForge {
    version = project.forge_version

    def atFile = file("src/main/resources/META-INF/accesstransformer.cfg")
    if (atFile.exists()) {
        accessTransformers {
            from atFile
            publish atFile
        }
    }

    //validateAccessTransformers.set(true)

    runs {
        client {
            client()
            systemProperty 'mixin.env.remapRefMap', 'true'
            systemProperty 'mixin.env.refMapRemappingFile', project.layout.buildDirectory.get().file('createSrgToMcp/output.srg').asFile.absolutePath
        }

        server {
            server()
            systemProperty 'mixin.env.remapRefMap', 'true'
            systemProperty 'mixin.env.refMapRemappingFile', project.layout.buildDirectory.get().file('createSrgToMcp/output.srg').asFile.absolutePath
            programArguments.add('--nogui')
        }

        data {
            data()
            programArguments.add("--all --mod the_bumblezone")
            programArguments.add("--existing ${project.project(":common").file("src/main/resources").absolutePath}")
            programArguments.add("--output ${project.project(":common").file("src/main/generated/resources").absolutePath}")
        }
    }

    mods {
        modServerRun {
            sourceSet sourceSets.main
            sourceSet project(":common").sourceSets.main
        }
    }
}

publishMods {
    file = tasks.reobfJar.archiveFile
    modLoaders.add("forge")

    File changeLog = rootProject.file("CHANGELOG.md")
    String changeLogText = changeLog.exists() ? changeLog.text : ""

    def uploadDependenciesCf = [
            "better-advancements": false
    ]
    def uploadDependenciesMr = [
            "better-advancements": false
    ]

    if (project.hasProperty('curseforge_id_forge')) {
        curseforge('CurseforgeForge') {
            accessToken = providers.environmentVariable('CURSEFORGEKEY')
            projectId = project.findProperty('curseforge_id_forge')
            minecraftVersions.add(project.minecraft_version)
            changelog = changeLogText

            uploadDependenciesCf.each { dep, required ->
                if (required) {
                    requires(dep)
                } else {
                    optional(dep)
                }
            }
        }
    }

    if (project.hasProperty('modrinth_id_forge')) {
        modrinth('modrinthForge') {
            accessToken = accessToken = providers.environmentVariable('MODRINTH_TOKEN')
            projectId = project.findProperty('modrinth_id_forge')
            minecraftVersions.add(project.minecraft_version)
            changelog = changeLogText

            dependencies {
                uploadDependenciesMr.each { dep, required ->
                    if (required) {
                        requires(dep)
                    } else {
                        optional(dep)
                    }
                }
            }
        }
    }
}

mixin {
    add(sourceSets.main, "${mod_id}.refmap.json")

    config("${mod_id}-common.mixins.json")
    config("${mod_id}-forge.mixins.json")
}

tasks.named("compileJava", JavaCompile) {
    source(project(":common").sourceSets.main.allJava)
}

tasks.named("javadoc", Javadoc) {
    source(project(":common").sourceSets.main.allJava)
}

tasks.named("sourcesJar", Jar) {
    from(project(":common").sourceSets.main.allSource)
}

processResources {
    from project(":common").sourceSets.main.resources
}

jar {
    manifest {
        attributes([
                "MixinConfigs": "${project.mod_id}-common.mixins.json,${project.mod_id}-forge.mixins.json"
        ])
    }
}

publishing {
    publications {
        "mavenJava"(MavenPublication) {
            from components.java
        }
    }
}