plugins {
    id 'net.neoforged.moddev'
    id 'net.fabricmc.fabric-loom-companion'
}

// Vanilla depends on ASM 9.3, MDG makes that a 'strict' version constraint,
// but Mixin and MixinExtras needs newer ASM so we override that here.
configurations.configureEach {
    resolutionStrategy.eachDependency { details ->
        if (details.requested.group == "org.ow2.asm") {
            details.useVersion(project.asm_version)
            details.because("Mixin requires new ASM")
        }
    }
}

configurations {
    runtimeClasspath.extendsFrom localRuntime
}

dependencies {
    // REQUIRED
    compileOnly "org.ow2.asm:asm:${project.asm_version}"
    compileOnly "org.ow2.asm:asm-analysis:${project.asm_version}"
    compileOnly "org.ow2.asm:asm-commons:${project.asm_version}"
    compileOnly "org.ow2.asm:asm-tree:${project.asm_version}"
    compileOnly "org.ow2.asm:asm-util:${project.asm_version}"

    compileOnly "net.fabricmc:sponge-mixin:${project.mixin_version}"
    compileOnly "io.github.llamalad7:mixinextras-common:${project.mixin_extras_version}"
    annotationProcessor "io.github.llamalad7:mixinextras-common:${project.mixin_extras_version}"

    compileOnly("earth.terrarium.athena:athena-neoforge-${project.athena}") { transitive = false  }
    compileOnly("com.teamresourceful.resourcefullib:resourcefullib-neoforge-${project.resourcefullib}") { transitive = false  }

    // COMPAT
    compileOnly("mezz.jei:jei-${project.jei_mc}-forge-api:${project.jei}") { transitive = false  }
    compileOnly("mezz.jei:jei-${project.jei_mc}-common-api:${project.jei}") { transitive = false  }
    compileOnly("dev.emi:emi-neoforge:${project.emi}:api") { transitive = false  }
    compileOnly("me.shedaniel:RoughlyEnoughItems-neoforge:${project.rei}") { transitive = false  }
    compileOnly("me.shedaniel:RoughlyEnoughItems-default-plugin:${project.rei}")
    compileOnly("dev.architectury:architectury-neoforge:${project.architectury}") { transitive = false  }
    compileOnly("me.shedaniel.cloth:cloth-config-neoforge:${project.cloth_config}") { transitive = false  }
    compileOnly("noobanidus.mods.lootr:lootr-neoforge:${project.lootr_version}") { transitive = false  }
    compileOnly("maven.modrinth:projectile-damage-attribute:${project.projectile_damage_attribute}-forge") { transitive = false  }
}

neoForge {
    neoFormVersion = project.neoform_version

    parchment {
        minecraftVersion = project.parchment_minecraft_version
        mappingsVersion = project.parchment_mappings_version
    }

    def atFile = file("src/main/resources/META-INF/accesstransformer.cfg")
    if (atFile.exists()) {
        accessTransformers {
            from atFile
            publish atFile
        }
    }

    validateAccessTransformers.set(true)
}
