plugins {
    id 'net.neoforged.moddev'
}

configurations {
    runtimeClasspath.extendsFrom localRuntime
}

repositories {
    exclusiveContent {
        forRepository {
            maven {
                name = "ModMaven"
                url = "https://modmaven.dev"
            }
        }
        filter {
            includeGroupAndSubgroups("com.hollingsworth.ars_nouveau")
            includeGroupAndSubgroups("mekanism")
        }
    }
    exclusiveContent {
        forRepository {
            maven {
                name = "C4's Maven"
                url = "https://maven.theillusivec4.top/"
            }
        }
        filter {
            includeGroupAndSubgroups("top.theillusivec4.curios")
            includeGroupAndSubgroups("com.illusivesoulworks.caelus")
        }
    }
    exclusiveContent {
        forRepository {
            maven {
                name = 'GeckoLib'
                url = 'https://dl.cloudsmith.io/public/geckolib3/geckolib/maven/'
            }
        }
        filter {
            includeGroup('software.bernie.geckolib')
        }
    }
    maven {
        url "https://maven.jamieswhiteshirt.com/libs-release"
        content {
            includeGroup "com.jamieswhiteshirt"
        }
    }
}

dependencies {
    // REQUIRED
    compileOnly(project(':common')) {
        transitive = false
    }

    runtimeOnly(compileOnly(jarJar("earth.terrarium.athena:athena-neoforge-${project.athena}")))
    runtimeOnly(compileOnly(jarJar("com.teamresourceful.resourcefullib:resourcefullib-neoforge-${project.resourcefullib}")))

    // COMPAT
    compileOnly("curse.maven:iron_jetpack-284497:${project.iron_jetpack_file_id}") { transitive = false }
    compileOnly("curse.maven:pneumaticcraft-281849:${project.pneumaticcraft_file_id}") { transitive = false }

    compileOnly("curse.maven:productive_bees-377897:${project.productivebees_file_id}") { transitive = false }

    // compileOnly("curse.maven:corail_tombstone-243707:6171577")

    compileOnly "noobanidus.mods.lootr:lootr-neoforge:${project.lootr_version}"
    // runtimeOnly("noobanidus.mods.lootr:lootr-neoforge:${project.lootr_version}")

    compileOnly("curse.maven:pokecube_aio-285121:${project.pokecubeaio_version}") { transitive = false }

    compileOnly("curse.maven:buzzier_bees-355458:${project.buzzier_bees_file_id}") { transitive = false }

    compileOnly("com.hollingsworth.ars_nouveau:ars_nouveau-${project.ars_nouveau}") { transitive = false }
    compileOnly("curse.maven:ars_elemental-561470:${project.ars_elemental_file_id}") { transitive = false }
    //runtimeOnly("com.hollingsworth.ars_nouveau:ars_nouveau-${project.ars_nouveau}") { transitive = false }
    //runtimeOnly("curse.maven:ars_elemental-561470:${project.ars_elemental_file_id}") { transitive = false }
    //runtimeOnly("top.theillusivec4.curios:curios-neoforge:${project.curios}")
    //runtimeOnly("software.bernie.geckolib:geckolib-neoforge-${minecraft_version}:${geckolib_version}")

    // runtimeOnly("curse.maven:better-advancements-272515:4631253")
    // runtimeOnly("curse.maven:spit-it-out-857141:4614678")
    // runtimeOnly("curse.maven:atlasviewer-633577:4597419")

    compileOnly("mekanism:Mekanism:${project.mekanism}:api")
//    runtimeOnly("mekanism:Mekanism:${project.mekanism}")// core
//    runtimeOnly("mekanism:Mekanism:${project.mekanism}:additions")// Mekanism: Additions
//    runtimeOnly("mekanism:Mekanism:${project.mekanism}:generators")// Mekanism: Generators
//    runtimeOnly("mekanism:Mekanism:${project.mekanism}:tools")// Mekanism: Tools

    compileOnly("mezz.jei:jei-${project.jei_mc}-neoforge:${project.jei}")
    compileOnly("mezz.jei:jei-${project.jei_mc}-common:${project.jei}")

    compileOnly("dev.emi:emi-neoforge:${emi}:api") { transitive = false }

    compileOnly("me.shedaniel:RoughlyEnoughItems-neoforge:${project.rei}") { transitive = false  }
    compileOnly("me.shedaniel:RoughlyEnoughItems-default-plugin:${project.rei}")

    compileOnly("maven.modrinth:projectile-damage-attribute:${project.projectile_damage_attribute}-forge") { transitive = false  }

    //runtimeOnly("top.theillusivec4.curios:curios-neoforge:${project.curios}")
    compileOnly("top.theillusivec4.curios:curios-neoforge:${project.curios}:api") { transitive = false }

//    runtimeOnly("curse.maven:worldedit-225608:4586218")
//    runtimeOnly("curse.maven:huge-structure-blocks-474114:5628956")
//    runtimeOnly("com.telepathicgrunt:CommandStructures-Neoforge:${project.commandstructures_neoforge}")
//    runtimeOnly("com.telepathicgrunt:StructureVoidToggle-Neoforge:${project.structurevoidtoggle_neoforge}")

    compileOnly("curse.maven:framedblocks-441647:${project.framedblocks_file_id}") { transitive = false }
}

publishMods {
    file = tasks.jar.archiveFile
    modLoaders.add("neoforge")

    File changeLog = rootProject.file("CHANGELOG.md")
    String changeLogText = changeLog.exists() ? changeLog.text : ""

    def uploadDependenciesCf = [
            "resourceful-lib": true,
            "better-advancements": false
    ]
    def uploadDependenciesMr = [
            "resourceful-lib": true,
            "better-advancements": false
    ]

    if (project.hasProperty('curseforge_id_neoforge')) {
        curseforge('CurseforgeNeo') {
            accessToken = providers.environmentVariable('CURSEFORGEKEY')
            projectId = project.findProperty('curseforge_id_neoforge')
            minecraftVersions.add(project.minecraft_version)
            changelog = changeLogText
            changelogType = "markdown"
            client = true
            server = true

            uploadDependenciesCf.each { dep, required ->
                if (required) {
                    requires(dep)
                } else {
                    optional(dep)
                }
            }
        }
    }

    if (project.hasProperty('modrinth_id_neoforge')) {
        modrinth('modrinthNeo') {
            accessToken = accessToken = providers.environmentVariable('MODRINTH_TOKEN')
            projectId = project.findProperty('modrinth_id_neoforge')
            minecraftVersions.add(project.minecraft_version)
            changelog = changeLogText

            dependencies {
                uploadDependenciesMr.each { dep, required ->
                    if (required) {
                        requires(dep)
                    } else {
                        optional(dep)
                    }
                }
            }
        }
    }
}

neoForge {
    version = project.neoforge_version

    parchment {
        minecraftVersion = project.parchment_minecraft_version
        mappingsVersion = project.parchment_mappings_version
    }

    def atFile = project(":common").file("src/main/resources/META-INF/accesstransformer.cfg")
    if (atFile.exists()) {
        accessTransformers {
            from atFile
            publish atFile
        }
    }

    validateAccessTransformers.set(true)

    mods {
        // define mod <-> source bindings
        // these are used to tell the game which sources are for which mod
        // mostly optional in a single mod project
        // but multi mod projects should define one per mod
        "${mod_id}" {
            sourceSet(sourceSets.main)
            sourceSet(project.project(":common").sourceSets.main)
        }
    }

    runs {
        configureEach {
            logLevel = org.slf4j.event.Level.DEBUG

            gameDirectory = project.file('run')

            sourceSet = sourceSets.main
            loadedMods.set([mods."${mod_id}"])
        }

        client {
            client()
            //systemProperty 'neoforge.enabledGameTestNamespaces', project.mod_id

            if (project.hasProperty('mc_uuid')) {
                programArguments.add("--uuid=${project.findProperty('mc_uuid')}")
            }

            if (project.hasProperty('mc_username')) {
                programArguments.add("--username=${project.findProperty('mc_username')}")
            }

            if (project.hasProperty('mc_java_agent_path')) {
                jvmArgument("-javaagent:${project.findProperty('mc_java_agent_path')}")
            }
        }

        server {
            server()
            systemProperty 'neoforge.enabledGameTestNamespaces', project.mod_id
            programArguments.add('--nogui')
        }

        data {
            data()
            programArguments.add("--all --mod the_bumblezone")
            programArguments.add("--existing ${project.project(":common").file("src/main/resources").absolutePath}")
            programArguments.add("--output ${project.project(":common").file("src/main/generated/resources").absolutePath}")
        }
    }
}

tasks.named("compileJava", JavaCompile) {
    source(project.project(":common").sourceSets.main.allJava)
}

tasks.named("javadoc", Javadoc) {
    source(project.project(":common").sourceSets.main.allJava)
}

tasks.named("sourcesJar", Jar) {
    from(project.project(":common").sourceSets.main.allSource)
}

processResources {
    from project.project(":common").sourceSets.main.resources
}
